### ISSUE TITLE
Tracking issue: netbench-orchestrator

### ISSUE THREAD

**Issue by toidiu** [aws/s2n-netbench#21]
## Goals
The goal of the Orchestrator is to automate Netbench runs in the cloud.

**Why?**
Often developers of transport protocols are interested in gathering performance data for the protocol they are developing. Netbench is a tool which can be used to measure this performance data. However, its often necessary to run Netbench scenarios in the cloud so that the results better match production systems.

## Project plan

Branch with working POC: https://github.com/aws/s2n-netbench/tree/ak-fullOrchImport

- [x] Russula: component to coordinate remote workers https://github.com/aws/s2n-netbench/pull/20
  - [x] https://github.com/aws/s2n-netbench/pull/29
  - [x] https://github.com/aws/s2n-netbench/pull/30
- [x] Aws utility wrappers
  - [x] s3 https://github.com/aws/s2n-netbench/pull/22
  - [x] ssm https://github.com/aws/s2n-netbench/pull/23
  - [x] ec2 https://github.com/aws/s2n-netbench/pull/26
- [x] Orchestrator
  - [x] base components (error, state) https://github.com/aws/s2n-netbench/pull/22
  - [x] cli https://github.com/aws/s2n-netbench/pull/26
  - [x] report, dashboad (index.html) https://github.com/aws/s2n-netbench/pull/27
  - [x] orchestrator run req_res.json https://github.com/aws/s2n-netbench/pull/28
